print("Herzlich willkommen in meinem ersten Programm, dieses Programm führt dich durch einige Fragen um die vlt für dich optimale Linux Distribution zu finden")
input("Um fortzufahren drücke bitte Enter")
print("welche Art von Distribution bevorzugst du")

print("(1) Ich möchte mein Linux von Anfang an selbst konfigurieren")
print("(2) Ich möchte ein fertiges System installieren welches direkt benutzt werden kann")

option = input("Wähle eine der beiden Optionen")
if int(option) == 1:
    print("bevorzugst du stabile oder schnelle Updates?")
    print("(1) stabil")
    print("(2) schnell")
    option = input("Wähle eine der beiden Optionen")
    if int(option) == 1:
        print("Du bist mir sehr sympatisch, ich mag Debian auch sehr gerne :)")
        print("       _,met$$$$$gg.")
        print("    ,g$$$$$$$$$$$$$$$P.")
        print("  ,g$$P\"\"       \"\"\"Y$$.")
        print(" ,$$P'              `$$$.")
        print("',$$P       ,ggs.     `$$b:")
        print("`d$$'     ,$P\"'   .    $$$")
        print(" $$P      d$'     ,    $$P")
        print(" $$:      $$.   -    ,d$$'")
        print(" $$;      Y$b._   _,d$P'")
        print(" Y$$.    `.`\"Y$$$$P\"'")
        print(" `$$b      \"-.__")
        print("  `Y$$")
        print("   `Y$$.")
        print("     `$$b.")
        print("       `Y$$b.")
        print("           `\"Y$b._")
        print("               `\"\"\"")
        quit()


    if int(option) ==2:
        print("Es sieht so aus als wärst du ein Arch User")
        print("                   -`")
        print("                  .o+`")
        print("                 `ooo/")
        print("                `+oooo:")
        print("               `+oooooo:")
        print("               -+oooooo+:")
        print("             `/:-:++oooo+:")
        print("            `/++++/+++++++:")
        print("           `/++++++++++++++:")
        print("          `/+++ooooooooooooo/`")
        print("         ./ooosssso++osssssso+`")
        print("        .oossssso-````/ossssss+`")
        print("       -osssssso.      :ssssssso.")
        print("      :osssssss/        osssso+++.")
        print("     /ossssssss/        +ssssooo/-`")
        print("   `/ossssso+/:-        -:/+osssso+-")
        print("  `+sso+:-`                 `.-/+oso:")
        print(" `++:.                           `-/+/")
        print(" .`                                 `/")
        quit()





if int(option) ==2:print("Du hast es also lieber bequem bei der Installation, das verstehe ich. Für dich gibt es extrem viele Distros zur Auswahl")
print("wie oft möchtest du dein system updaten?")
print("(1) Nie, ich möchte ein Roling Release System")
print("(2) Etwa jedes halbe Jahr")
print("(3) so alle 2-3 Jahre")
option = input("Wähle eine Option")
if int(option) == 1:
    print("bevorzugst du pacman oder rpm?")
    print("(1) Pacman")
    print("(2) RPM")
    option = input("Wähle eine Option")
    if int(option) == 1:
        print("Hier hast du 3 zur Auswahl, entscheide dich")
        print("(1) Manjaro, manche behaupten es sei gut für Einsteiger, andere finden es instabiler als reines Arch")
        print("(2) Endevour OS, im Prinzip ein reines Arch Linux das per Calamares installiert wird, im Gegensatz zu Arch aber schon einige Tools mitbringt")
        print("(3) Cachy OS, die aktuell gehypteste Linux Distro überhaupt, durch einen optimierten Kernel richtet sich dieses System besonders an Gamer")
        option = input("Wähle eine Option")
        if int(option) == 1:
            print:("Manjaro")
            print(" ██████████████████  ████████   ")
            print(" ██████████████████  ████████   ")
            print(" ██████████████████  ████████   ")
            print(" ██████████████████  ████████    ")
            print(" ████████            ████████   ")
            print(" ████████  ████████  ████████    ")
            print(" ████████  ████████  ████████   ")
            print(" ████████  ████████  ████████   ")
            print(" ████████  ████████  ████████    ")
            print(" ████████  ████████  ████████    ")
            print(" ████████  ████████  ████████    ")
            print(" ████████  ████████  ████████    ")
            print(" ████████  ████████  ████████     ")
            quit()

        if int(option) == 2:
            print("Endevour OS, mein Lieblings Arch :)")
            print("Leider kein Logo")
            quit()
            
        if int(option) == 3:
            print("    .-------------------------:                   ")
            print("           .+=========================.                    ")
            print("          :++===++==================-       :++-         ")
            print("         :*++====+++++=============-        .==:          ")
            print("        -*+++=====+***++==========:                        ")
            print("       =*++++========------------:                        ")
            print("      =*+++++=====-                     ...                ")
            print("    .+*+++++=-===:                    .=+++=:             ")
            print("   :++++=====-==:                     -*****+              ")
            print("  :++========-=.                      .=+**+.              ")
            print(" .+==========-.                          .                 ")
            print("  :+++++++====-                                .--==-.    ")
            print("   :++==========.                             :+++++++:   ")
            print("    .-===========.                            =*****+*+   ")
            print("     .-===========:                           .+*****+:    ")
            print("       -=======++++:::::::::::::::::::::::::-:  .---:      ")
            print("        :======++++====+++******************=.             ")
            print("         :=====+++==========++++++++++++++*-               ")
            print("          .====++==============++++++++++*-                ")
            print("           .===+==================+++++++:                 ")
            print("            .-=======================+++:  ")
            quit()
            





    if int(option) == 2:
        print("Viel Spaß mit Opensuse Tumbleweed")
        print("                                         ")
        print("                                         ")
        print("            .;ldkO0000Okdl;.               )")
        print("        .;d00xl:^''''''^:ok00d;.         ")
        print("      .d00l'                'o00d.         ")
        print("    .d0Kd'  Okxol:;,.          :O0d        ")
        print("   .OKKKK0kOKKKKKKKKKKOxo:,      lKO.     ")
        print("  ,0KKKKKKKKKKKKKKKK0P^,,,^dx:    ;00,     ")
        print(" .OKKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.   ")
        print(" :KKKKKKKKKKKKKKKKK: kKx..dd lKd   'OK:   ")
        print(" dKKKKKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd   ")
        print(" dKKKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd   ")
        print(" :KKKKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:    ")
        print("  kKKKKKKKKKKKKKKK0x;,,......,;od  lKk   ")
        print("  '0KKKKKKKKKKKKKKKKKKKKK00KKOo^  c00'    ")
        print("   'kKKKOxddxkOO00000Okxoc;''   .dKk'      ")
        print("     l0Ko.                    .c00l'       ")
        print("      'l0Kk:.              .;xK0l'        ")
        print("         'lkK0xl:;,,,,;:ldO0kl'           ")
        print("             '^:ldxkkkkxdl:^'         ")
        quit()




if int(option) == 2:
    print("legst du großen Wert auf NUR freie Software?")
    print("(1) Ja")
    print("(2) Nein")
    option = input("Wähle eine Option")
    if int(option) == 1:
        print("Wie wäre es mit Fedora Workstation")
        print("            .',;::::;,'.                 ")
        print("          .';:cccccccccccc:;,.             ")
        print("       .;cccccccccccccccccccccc;.         ")
        print("     .:cccccccccccccccccccccccccc:.        ")
        print("   .;ccccccccccccc;.:dddl:.;ccccccc;.      ")
        print("  .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    ")
        print(" .:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.   ")
        print(" ,cccccccccccccc;MMM.;cc;;WW:;cccccccc,    ")
        print(" :cccccccccccccc;MMM.;cccccccccccccccc:    ")
        print(" :ccccccc;oxOOOo;MMM000k.;cccccccccccc:    ")
        print(" cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;    ")
        print(" ccccc;XMO';cccc;MMM.;cccccccccccccccc'   ")
        print(" ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    ")
        print(" ccccc;0MNc.ccc.xMMd;ccccccccccccccc;      ")
        print(" cccccc;dNMWXXXWM0:;cccccccccccccc:,      ")
        print(" cccccccc;.:odl:.;cccccccccccccc:,.       ")
        print(" ccccccccccccccccccccccccccccc:'.         ")
        print(" :ccccccccccccccccccccccc:;,..             ")
        print("  ':cccccccccccccccc::;,.              ")
        quit()

        
    if int(option) == 2:
        print("Probier doch eine STS Ausgabe von Ubuntu")
        print("                ....              ")
        print("               .',:clooo:  .:looooo:.          ")
        print("            .;looooooooc  .oooooooooo'        ")
        print("         .;looooool:,''.  :ooooooooooc        ")
        print("        ;looool;.         'oooooooooo,         ")
        print("       ;clool'             .cooooooc.  ,,       ")
        print("          ...                ......  .:oo,      ")
        print("   .;clol:,.                        .loooo'     ")
        print("  :ooooooooo,                        'ooool     ")
        print(" 'ooooooooooo.                        loooo.   ")
        print(" 'ooooooooool                         coooo.    ")
        print("  ,loooooooc.                        .loooo.    ")
        print("    .,;;;'.                          ;ooooc     ")
        print("        ...                         ,ooool.     ")
        print("     .cooooc.              ..',,'.  .cooo.     ")
        print("       ;ooooo:.           ;oooooooc.  :l.       ")
        print("        .coooooc,..      coooooooooo.          ")
        print("          .:ooooooolc:. .ooooooooooo'         ")
        print("            .':loooooo;  ,oooooooooc            ")
        print("                ..';::c'  .;loooo:'            ")
        quit()

if int(option) ==3:
    print("Welche Art von Oberfläche bevorzugts du?")
    print("(1)Ich bevorzuge einen Desktop ähnlich zu Windows ")
    print("(2)ich bevorzuge einen Desktop ähnlich zu Mac ")
    print("(3) Die Oberfläche ist mir egal, gib mir das beste Was es gibt!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    option = input("Wähle eine Option")
    if int(option) == 1: 
        print("Linux Mint ist ein tolles Gesamtpaket")
        print("              ...-:::::-...                 ")
        print("           .-MMMMMMMMMMMMMMM-.         ")
        print("       .-MMMM`..-:::::::-..`MMMM-.        ")
        print("     .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.       ")
        print("    -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-   ")
        print("  `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    ")
        print("  :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:   ")
        print(" .MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.    ")
        print(" :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   ")
        print(" :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:    ")
        print(" :MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   ")
        print(" .MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   ")
        print("  :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:   ")
        print("   :MMM:MMM:`                `:MMM:MMM:  ")
        print("    .MMM.MMMM:--------------:MMMM.MMM.      ")
        print("      '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       ")
        print("        '.-MMMM``--:::::--``MMMM-.'         ")
        print("             '-MMMMMMMMMMMMM-'            ")
        print("                ``-:::::-``                 ")
        quit()

    if int(option) == 2:
        print("Ubuntu LTS bietet neben einem modifiziertem Gnome bis zu 10 Jahre kostenlosen Support")
        print("                ....              ")
        print("               .',:clooo:  .:looooo:.          ")
        print("            .;looooooooc  .oooooooooo'        ")
        print("         .;looooool:,''.  :ooooooooooc        ")
        print("        ;looool;.         'oooooooooo,         ")
        print("       ;clool'             .cooooooc.  ,,       ")
        print("          ...                ......  .:oo,      ")
        print("   .;clol:,.                        .loooo'     ")
        print("  :ooooooooo,                        'ooool     ")
        print(" 'ooooooooooo.                        loooo.   ")
        print(" 'ooooooooool                         coooo.    ")
        print("  ,loooooooc.                        .loooo.    ")
        print("    .,;;;'.                          ;ooooc     ")
        print("        ...                         ,ooool.     ")
        print("     .cooooc.              ..',,'.  .cooo.     ")
        print("       ;ooooo:.           ;oooooooc.  :l.       ")
        print("        .coooooc,..      coooooooooo.          ")
        print("          .:ooooooolc:. .ooooooooooo'         ")
        print("            .':loooooo;  ,oooooooooc            ")
        print("                ..';::c'  .;loooo:'            ") 
        quit()
    if int(option) == 3:
        print("Guide OS")
        print("            .::::..::::.         ")
        print("         .::.      ......:.      ")
        print("       .:.           .::. .:     ")
        print("     .:          .:.  :::: .:     ")
        print("   .:.       ..:::.   ::::. :     ")
        print("  ...    ..:..::::    ::::: .     ")
        print("  .:         ::::    .::::.       ")
        print(" . :         .::    .:::::        ")
        print(" .. .         :   .:::.::         ")
        print(" .:: ..         .::::::.          ")
        print(" .::::.......::::::::.            ")
        print("  .::::::::::::::::.              ")
        print("    ..:::::::...                   ")
        quit()
